services:
    sr-ros2-core:
      container_name: sr-ros2
      image: ghcr.io/tud-cor-sr/sr-ros2-bundles:main
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - DISPLAY=:0
        - QT_X11_NO_MITSHM=1
      privileged: true
    sr-ros2-macos:
      extends: sr-ros2-core
      volumes:
          - type: bind
            source: /tmp/.X11-unix
            target: /tmp/.X11-unix
    sr-ros2-ubuntu:
      extends: sr-ros2-core
      build:
        network: host
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,display
      network_mode: host
      runtime: nvidia
    sr-ros2-windows:
      extends: sr-ros2-core
      environment: 
        - DISPLAY=host.docker.internal:0
      ports:
        # for communication through MODBUS / TCP with VTEM motion terminal
        - target: 502
          published: 502
          protocol: tcp
      