services:
    sr-ros2-core:
      container_name: sr-ros2
      image: ghcr.io/tud-cor-sr/sr-ros2-bundles:main
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - DISPLAY=:0
        - QT_X11_NO_MITSHM=1
      ports:
        # for communication through MODBUS / TCP with VTEM motion terminal
        - target: 502
          published: 502
          protocol: tcp
      privileged: true
    sr-ros2-macos:
      extends: sr-ros2-core
      volumes:
          - type: bind
            source: /tmp/.X11-unix
            target: /tmp/.X11-unix
    sr-ros2-ubuntu:
      extends: sr-ros2-core
      build:
        network: host
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,display
      # this somehow doesnt work
      # gpus: all
      network_mode: host
      runtime: nvidia
    sr-ros2-windows:
      extends: sr-ros2-core
      environment: 
        - DISPLAY=host.docker.internal:0
      # ports:
        # CYCLONE_DDS communication between Docker container and host system
        # https://github.com/eclipse-cyclonedds/cyclonedds/issues/677#issuecomment-768966870
        # - "192.168.200.169:7412:7412/udp"
        # - "192.168.200.169:7413:7413/udp"
      